paises = []
paises.append('estados unidos')
paises.append('australia')
paises.insert(0, 'canada')
paises.insert(3,'egito')
print(paises)
print(sorted(paises))
print(paises)
print(sorted(paises, reverse=True))
print(paises)
paises.reverse()
print(paises)
paises.reverse()
print(paises)
paises.sort()
print(paises)
paises.sort(reverse=True)
print(paises)
